[package]
name = "generic-camera-asi"
version = "0.0.1"
edition = "2021"
rust-version = "1.68.0"
authors = ["Sunip K. Mukherjee"]
license = "MIT OR Apache-2.0"
readme = "README.MD"
repository = "https://github.com/sunipkm/generic-camera-asi"
homepage = "https://crates.io/crates/generic-camera-asi"
keywords = ["generic-camera", "interface", "api", "zwo", "asi"]
build = "build.rs"
description = """
An efficient and ergonomic interface to capture images using cameras.
"""
exclude = [".github"]

[[bin]]
name = "asigeneric_capture"
path = "src/main.rs"
test = true
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-camera = { path = "../generic_camera" }
refimage = { version = "<1.0", features = ["rayon", "fitsio", "serde_flate"]}
cameraunit = "5.1"
chrono = "0.4"
configparser = "3.0"
ctrlc = "3.4"
fitsio = "0.21"
image = "0.25"
log = "0.4"
bytemuck = "1.18.0"
lazy_static = "1.5.0"

[build-dependencies]
bindgen = "0.68.1"
cc = "1.0.83"
