[package]
name = "gencam_asi_example"
version = "0.0.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
configparser = "3.1.0"
ctrlc = "3.4.5"
generic-camera-asi = { path = "../" }
refimage = { version = ">= 0.10", features = ["default", "image", "fitsio"] }
image = "0.25"
gencam_packet = { path = "../../gencam_packet" }
serde = "1.0.210"
serde_json = "1.0.128"
tungstenite = { version = "0.23.0" }